### ISSUE TITLE
Bug when using plugin with class selectors

### ISSUE THREAD

**Issue by phaeton2040** [senthilporunan/jRate#10]
I'm trying to use your plugin with class selectors. Html is rendered but only first element is colored on hover

**Comment by senthilporunan** [comment]
Let me know the configurations you tried there.

**Comment by phaeton2040** [comment]
Solved it:
$('.my-class').each(function(i,v){
    $(v).jRate(options)
});

**Comment by senthilporunan** [comment]
Sounds good :+1: Let us know if you need more information. I am closing this issue.
