### ISSUE TITLE
Multiple events on setting a value

### ISSUE THREAD

**Issue by vikas-jha** [senthilporunan/jRate#13]
When I click the widget to rate an item the method in onSet is called twice.

**Comment by senthilporunan** [comment]
Hi,

Its calling for one time only. Please find the jsfiddle http://jsfiddle.net/3zmk8r1s/ 
for it. 

If you are still facing the issue, please share your configurations.

**Comment by princejwesley** [comment]
@vikas-jha Make sure that you have latest version

**Comment by vikas-jha** [comment]
Thanks for helping me. It seems that there is some issue with my code. I'll try to fix it.
