### ISSUE TITLE
How to get value from selected star and store it in database using jquery or javascript

### ISSUE THREAD

**Issue by usamamashkoor** [senthilporunan/jRate#14]
I am trying to get value from Jrate Plugin for example when the using click on 3rd start the value should i get should must be 3.and i can get it on using jRate onSet option
$("#jRate").jRate({
					onSet: function(rating) {
						alert("Selected Rating: "+rating);
					}
				});
but i dont want to get the value on onSet function i want value when user click on save button  just like how we get value from inout box $('#inputbox'),val(); 
Is their any way i can get value like this..

**Comment by senthilporunan** [comment]
Hi,

You can use below piece of code.

For Eg:
			var toolitup = $("#jRate").jRate({
				rating: 1,
				strokeColor: 'black',
				width: 80,
				height: 80,
				precision: 0.1,
				minSelected: 1
			});
			
			$('#btn-click').on('click', function() {
				var value = toolitup.getRating();				
				console.log("New Value: "+value);
			});

Thanks,
Senthil.

**Comment by usamamashkoor** [comment]
Thnx Bro
