### ISSUE TITLE
Multiple jRates in FireFox and Internet Explorer

### ISSUE THREAD

**Issue by Krazyhawk1993** [senthilporunan/jRate#16]
I have a set up where I call multiple jRates through an Ajax request on the same page (10 to be exact), each is supposed to have a separate rating. The settings are dynamically created with a default value / read only etc. In Chrome there are no problems, every one has it's correct value. In Mozilla FireFox and Internet Explorer the following 9 jRates take the value from the 1st one, to which I can not override even if I hard code a number. I have tried everything from spacing out the divs to making them separate scripts, nothing is working. I am not sure why Google Chrome has no problem with this but the other two do, if this fails I will just have to use images, but I would like to resolve the issue.

There is also another jRate called WAY earlier in the script that has no problems at all, if that is any help. The 10 that are problematic are called one after the other, each within a respective span inside a paragraph tag. I am not sure if the consecutive calls are causing it to fail or if there is another underlying factor.

Thank you for your time.

**Comment by master412160** [comment]
Hey is it easy or hard to make this rating plugin work on a board like phpbb? In other words I'm looking to make it work for each seperate row like you did.

**Comment by Krazyhawk1993** [comment]
It is actually pretty easy, though the jRate function itself is a little touchy when i comes to multiple calls. For example, you cannot establish all rules such as size, color, etc. in one call. So each time you call the function, you have to establish this, which gets a little repetitive.  The calls themselves are located after a query has been made to the database, so all that is left to do is call the function like normal (through an echo) and plug in the variables where they need to be.

<script type="text/JavaScript">$(".overall").jRate({ startColor: "darkred", endColor: "darkred", count: 5, precision: 0.1, width: 30, height: 30, readOnly: true, rating: ' . $g["overall"] . ' });

Here is an example using a stored number from my database, in this case "overall" will be a number between 0 and 5.

WARNING: At this moment my consecutive calls are not working in firefox or IE (both updated), but works in Google Chrome. Have not tested other browsers.

Hope this answers your question my man.

Oh, and in case you were looking for an example on the onChange and onSet, since I only found the generic ones, here is a slither of my code: 

$('#userRating').jRate({
				startColor: "darkred", 
				endColor: "darkred", 
				count: 5, 
				precision: 0.1,
				height: 40,
				width: 40,
				rating: 2.5,
				onChange: function(rating) {
					$('#ratingWritten').html('<span class="voteEmphasis">(' + rating + '</span> / 5<span class="voteEmphasis">)</span>');
				},
				onSet: function(rating) {
					var game = $('#userRating').data('game');
					if(window.XMLHttpRequest) {
						//modern browsers (IE7+)
						xmlhttp = new XMLHttpRequest();
					} else {
						//IE 5 + 6
						xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
					}
					xmlhttp.onreadystatechange = function() {
						if(xmlhttp.readyState == 4 && xmlhttp.status == 200) {
							$('.ratingBox').html(xmlhttp.responseText);
							$('.userVote').css('visibility', 'hidden');
							$('.ratingBox, #sideContent').delay(3000).fadeOut(500, function() {
								<?php echo 'window.location.href="' . $root . '/index.php?g=" + game;'; ?>
							});
						}
					}
					xmlhttp.open("GET", "scripts/userRating.php?r=" + rating + "&g=" + game, true);
					xmlhttp.send();
				}
			});

Hope it helps!

**Comment by master412160** [comment]
Prince why did you close this? You didn't provide an answer to the OP.

**Comment by Krazyhawk1993** [comment]
Though I am more than displeased that this was closed without either answering OR even a comment saying anything. After an entire morning of experimenting I have found the issue. My current versions of FireFox and IE are having trouble with the SVG's directly. Since the plugin creates each star via SVG you can see this is a problem. The two problematic browsers seem to have some sort of capacity, whatever the first coordinates / color is, it replicates that through each and every svg, hence why I am getting the wrong result. This is not a problem with jRate directly, it seems to be a browser issue. Though the method jRate uses to create the stars is the problem (though I don't blame them for that, this is on IE and FireFox). 

I have no solution for this at this time, I am seeking alternatives.

FireFox: 38.0.5

IE: 11.0.21

**Comment by princejwesley** [comment]
@Krazyhawk1993 @master412160 Sorry, I thought that @Krazyhawk1993  got a solution. Can you provide a sample (jsfiddle, plunker or codepen) to work on?

**Comment by Krazyhawk1993** [comment]
I would but I have never used those, and after 20 mins couldn't get jRate to work at all in jsfiddle.

**Comment by senthilporunan** [comment]
@Krazyhawk1993 .. you can share your sample code through jsfiddle or pastebin. If its not working also, we are fine. We will fix the code and let you know.

**Comment by senthilporunan** [comment]
IE and firefox older version is not supporting svg. so, i am closing this issue. Let us know if you are facing any issue in latest browser version.
