### ISSUE TITLE
New Icon Support from Reza Hafezi

### ISSUE THREAD

**Issue by senthilporunan** [senthilporunan/jRate#18]
hi my friend. 

I want use jRate in my project but I need to change shape of star to shopping basket. could you please make it for me? 

I attach you my shopping basket icon in svg format. please work on this icon. 

many many thanks bro.

**Comment by rezahafezi** [comment]
many thanks Senthil

could you please tell me when you can add this shape? because my project is forced and I haven't much time. 

many thanks

**Comment by senthilporunan** [comment]
Hopefully, tomorrow, we will able to deliver after all rounds of testing.

**Comment by rezahafezi** [comment]
many many thanks bro <3

good luck

**Comment by senthilporunan** [comment]
HI, we have added new shape (Basket) based upon your requirements. Please use the version 1.2.5 onwards. 
![jrate_basket](https://cloud.githubusercontent.com/assets/9432059/9231919/6ca440ca-4148-11e5-9dc6-92402a66e699.PNG)

We have completed all rounds of testing. Let us know if you need more information.

**Comment by rezahafezi** [comment]
hi dear Senthil.

many many many thanks for your awesome support. your plugin work amazing
for me.

but I have 2 question:

1- why basket filled from right to left in my case? I attach a photo to
understand it.

2- I want to show value of rate as a number. how can I do it?

thanks

On Wed, Aug 12, 2015 at 10:19 PM, Senthil Porunan <notifications@github.com>
wrote:

> Closed #18 <https://github.com/senthilporunan/jRate/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/senthilporunan/jRate/issues/18#event-380592523>.
>



-- 
------------------------
*Reza Hafezi*

**Comment by senthilporunan** [comment]
hi,

![image](https://cloud.githubusercontent.com/assets/9432059/9250443/8d4b6b80-41ea-11e5-91ec-9ed70c6114f1.png)

You can change the configuration when you are calling jRate api.

Like this: 
```javascript
			var toolitup = $("#jRate").jRate({
				rating: 1,
				strokeColor: 'black',
				width: 50,
				height: 50,
				precision: 0.1,
				reverse: true,
				shape: 'BASKET',
				onSet: function(rating) {
					$('#demo-onset-value').val(rating);
				}
			});
```javascript

**Comment by rezahafezi** [comment]
wow! many thanks bro. you are amazing. my problem is solved.

good luck

On Thu, Aug 13, 2015 at 5:40 PM, Senthil Porunan <notifications@github.com>
wrote:

> hi,
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9432059/9250443/8d4b6b80-41ea-11e5-91ec-9ed70c6114f1.png>
>
> You can change the configuration when you are calling jRate api.
>
> Like this:
>
>             var toolitup = $("#jRate").jRate({
>                 rating: 1,
>                 strokeColor: 'black',
>                 width: 50,
>                 height: 50,
>                 precision: 0.1,
>                 reverse: true,
>                 shape: 'BASKET',
>                 onSet: function(rating) {
>                     $('#demo-onset-value').val(rating);
>                 }
>             });```javascript
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/senthilporunan/jRate/issues/18#issuecomment-130663868>
> .
>



-- 
------------------------
*Reza Hafezi*

**Comment by rezahafezi** [comment]
sorry S*enthil for my lots question. I promise this i*s last one :))

how can I show the MAX value as a text in my project?

On Thu, Aug 13, 2015 at 6:35 PM, Reza Hafezi <reza.hafezi.63@gmail.com>
wrote:

> wow! many thanks bro. you are amazing. my problem is solved.
>
> good luck
>
> On Thu, Aug 13, 2015 at 5:40 PM, Senthil Porunan <notifications@github.com
> > wrote:
>
>> hi,
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/9432059/9250443/8d4b6b80-41ea-11e5-91ec-9ed70c6114f1.png>
>>
>> You can change the configuration when you are calling jRate api.
>>
>> Like this:
>>
>>             var toolitup = $("#jRate").jRate({
>>                 rating: 1,
>>                 strokeColor: 'black',
>>                 width: 50,
>>                 height: 50,
>>                 precision: 0.1,
>>                 reverse: true,
>>                 shape: 'BASKET',
>>                 onSet: function(rating) {
>>                     $('#demo-onset-value').val(rating);
>>                 }
>>             });```javascript
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/senthilporunan/jRate/issues/18#issuecomment-130663868>
>> .
>>
>
>
>
> --
> ------------------------
> *Reza Hafezi*
>



-- 
------------------------
*Reza Hafezi*

**Comment by senthilporunan** [comment]
I am not getting your question clearly. Please tell some scenario.
