### ISSUE TITLE
Use of Id Causing Problems

### ISSUE THREAD

**Issue by graphnick** [senthilporunan/jRate#19]
I really like the potential that jRate has. However, I have discovered that an ID attribute is required to use jRate. The issue doesn't show up until many instances of jRate get placed in the DOM. There is an assumption that an ID is on the node in which jRate is called, but that should not always be assumed. I typically don't use id's to reference objects, but rather more general data attribute such as [data-js-ratings="x.x"] as it is easier to loop through multiple items in the DOM using:
```javascript
var $ratings = $('[data-js-ratings]');

$ratings.each(function(index){
  var $curRating = $(this);

  $curRating.attr('id', 'jrate'+index); // setting an ID here should not be required

  var rate = $curRating.data('js-ratings');
  $curRating.jRate({
	rating: rate,
	readOnly: true
 });
});
```
In my case I use jRate to apply over 60 ratings from a DB on a page. The reference data-js-ratings will loop through each node and apply the rating accordingly. The problem is if there is no id the reference in the jRate script references "undefined" and the scope on which star needing to set gets confused as multiple svg items with the same ID get placed in the DOM and there can be only one unique ID per DOM. Why scope things using an ID anyway? There are more efficient ways to do a lookup than through an ID. 

For now, I have put an ID on the item in my loop according to the index, but shouldn't be necessary.

I suggest using the data attribute to hold the references to stars, so that the setting/changing of the stars doesn't have to lookup and search through the DOM using find. The scope should remain within the node component and not traverse elsewhere. Using ID to find in inner item is the root of the issue.

**Comment by senthilporunan** [comment]
Thanks your suggestions are good and valid. We will look into it.

**Comment by senthilporunan** [comment]
Hi, 

We have changed the code and testing got completed. As the code changes are minimal, we will combine with some other release.

**Comment by graphnick** [comment]
Thank you

Nick Haroldsen
*GraphNick*
* Design**http://graphnickdesign.com <http://graphnickdesign.com/>*

**Comment by capensisma** [comment]
@senthilporunan this is still the case and NOT solved you should either FIX this or add it as a note in the docs!!! I have spent hours trying to debug this issue!! 

Who would add ids when using a class for multiple items bro?
