### ISSUE TITLE
Display issue when combining precision with min, max or count

### ISSUE THREAD

**Issue by rbatemangazelle** [senthilporunan/jRate#4]
$('#item').jRate({precision: 0});  works as expected - the Star or other items only highlight in full.  If you combine precision with min, max or count, though (e.g. $('#item').jRate({min: 1, max: 7, count: 7, precision: 0}); ), the Star or other items will be partially highlighted instead of highlighted in full.  rating returns correctly as a whole number, but the display is misleading as the last item may be partially selected.

![screenshot](https://cloud.githubusercontent.com/assets/10763401/5965665/d79e40b8-a7cb-11e4-9579-2c62a72dea20.png)

**Comment by rbatemangazelle** [comment]
I've realized that this is more of a documentation issue.  If I use {min: 0, max: 7, count: 7, precision: 0}, then it works as expected.  The confusion arose in that it wasn't clear to me that the min value is actually the value when no items are selected.  In essence, when precision is 0, max minus min should equal count.

**Comment by senthilporunan** [comment]
User accepted this is not an issue. So, i am closing this one.
