### ISSUE TITLE
Setting min breaks the view

### ISSUE THREAD

**Issue by disav1** [senthilporunan/jRate#8]
var rater = $("#jRate").jRate({
            startColor: "#6eb9e1",
            endColor: "#6eb9e1",
            backgroundColor: '#999999',
            rating: 3,
            precision: 0,
            min: 1});

![image](https://cloud.githubusercontent.com/assets/6671446/7107659/b72b845c-e174-11e4-8995-d9795248a8cc.png)

**Comment by senthilporunan** [comment]
Hi ,

This is working as per design document. minvalue says about starting_value and maxvalue saying about ending_value. In your case, you can change min: 0, max: 5 , it will work as per your expectations. 

Above your example, you are setting starting_value (min) as 1 and ending_value(max) as 5 (default value). So, its evenly distributing 4(5-1) to 5 stars.

Let me know if you need more information.

Thanks,
Senthil.

**Comment by disav1** [comment]
Ok I misunderstood how min value works then. But what if I want 5 stars from 1 to 5 and 0 cannot be selected.
If I set min: 0 max: 5 then the user can set 0 rating which I don't want to allow.

**Comment by senthilporunan** [comment]
Oops. We did n't thought about this use case. We will modify and publish
with in one or two days.

Thanks for informing us.

Cheers,
Senthil.
@senthilporunan
www.toolitup.com

**Comment by senthilporunan** [comment]
Hi, 

Introduced new parameter called minSelected. User have no rights to select lesser than the value which you mentioned in minSelected parameter. I hope that will help you to solve your problem.  

Cheers,
Senthil.
@senthilporunan
www.toolitup.com

**Comment by disav1** [comment]
Thanks, Senthil. That is exactly what I wanted.
