### ISSUE TITLE
Set star border style

### ISSUE THREAD

**Issue by phaeton2040** [senthilporunan/jRate#9]
Hi! Thanks for your project!
I need stars to be transparent with white borders when rating not set. Is there any way to do this?

**Comment by senthilporunan** [comment]
Currently, our plugin is not supporting transparency layer. We will take this as an enhancement in our next release and we will release it.

**Comment by princejwesley** [comment]
[Color transparency] (https://github.com/senthilporunan/jRate#color-transparency) feature is added
